import { useEffect, useState } from "react";
import Head from "next/head";
import { io } from "socket.io-client";
import ExchangesOperation from "./components/exchangesOperation/ExchangesOperation";
import ExchangesHistory from "./components/exchangesHistory/ExchangesHistory";
import CurrencyHistory from "./components/currencyHistory/CurrencyHistory";
import styles from "../styles/Home.module.css";

export const socket = io("http://localhost:3000");

const I18NStorageKey = "i18nextLng";

export default function Home() {
  const [lang, setLang] = useState("");

  useEffect(() => {
    if (typeof window !== "undefined") {
      setLang(localStorage.getItem(I18NStorageKey));
    }
  }, []);

  const handleChangeLanguage = (e: string) => {
    localStorage.setItem(I18NStorageKey, e);
    setLang(localStorage.getItem(I18NStorageKey));
    window.location = window.location;
  };

  return (
    <div>
      <Head>
        <title>Forex Trading App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className={styles.appHeader}>
          <h1 className={styles.pageTitle}>Dashboard</h1>
          <select
            data-testid="langSelector"
            className={styles.langSelector}
            name="lang"
            id="lang"
            onChange={(e) => handleChangeLanguage(e.target.value)}
            value={lang}
          >
            <option value="en-US">English</option>
            <option value="pt-BR">Portuguese</option>
          </select>
        </header>
        <div className={styles.section}>
          <CurrencyHistory />
          <ExchangesOperation />
        </div>
        <ExchangesHistory />
      </main>
    </div>
  );
}
